In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\ashib\OneDrive\Desktop\customer_data.csv",usecols=['education','loyalty_status','promotion_usage'],skiprows=[500,15000])
df

education loyalty_status  promotion_usage
0        Bachelor           Gold                0
1         Masters        Regular                1
2        Bachelor         Silver                0
3      HighSchool        Regular                0
4         College        Regular                1
...           ...            ...              ...
99993     College        Regular                0
99994  HighSchool        Regular                0
99995     College        Regular                0
99996    Bachelor        Regular                1
99997     College         Silver                0

[99998 rows x 3 columns]

In [17]:
df.sample(5)

education loyalty_status  promotion_usage
61034  Bachelor        Regular                0
96852   Masters         Silver                0
38801  Bachelor        Regular                0
33937  Bachelor        Regular                0
29874   Masters           Gold                1

In [18]:
df.isnull().sum()

education          0
loyalty_status     0
promotion_usage    0
dtype: int64

In [5]:
df=df[df['education']!='College']
df

education loyalty_status  promotion_usage
0        Bachelor           Gold                0
1         Masters        Regular                1
2        Bachelor         Silver                0
3      HighSchool        Regular                0
5        Bachelor         Silver                0
...           ...            ...              ...
99989    Bachelor        Regular                0
99990  HighSchool         Silver                0
99992  HighSchool        Regular                0
99994  HighSchool        Regular                0
99996    Bachelor        Regular                1

[60126 rows x 3 columns]

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [24]:
X_train

education loyalty_status
93173     Masters        Regular
62497    Bachelor         Silver
15266    Bachelor         Silver
23601     Masters         Silver
15950  HighSchool        Regular
...           ...            ...
76898  HighSchool        Regular
78546     Masters        Regular
82198    Bachelor        Regular
61322  HighSchool         Silver
16310     Masters        Regular

[48100 rows x 2 columns]

In [7]:
from sklearn.preprocessing import OrdinalEncoder


In [26]:
oe=OrdinalEncoder(categories=[['HighSchool','Bachelor','Masters'],['Regular','Silver','Gold']])

In [27]:
oe.fit(X_train)

OrdinalEncoder(categories=[['HighSchool', 'Bachelor', 'Masters'],
                           ['Regular', 'Silver', 'Gold']])

In [13]:
X_train['education'].unique()

array(['HighSchool', 'Bachelor', 'Masters'], dtype=object)

In [14]:
X_train['loyalty_status'].unique()

array(['Silver', 'Gold', 'Regular'], dtype=object)

In [28]:
X_train=oe.transform(X_train)

In [29]:
X_test=oe.transform(X_test)

In [30]:
X_train

array([[2., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [2., 0.]], shape=(48100, 2))

In [31]:
oe.categories_

[array(['HighSchool', 'Bachelor', 'Masters'], dtype=object),
 array(['Regular', 'Silver', 'Gold'], dtype=object)]

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le=LabelEncoder()


In [34]:
le.fit(y_train)

LabelEncoder()

In [36]:
le.classes_

array([0, 1])

In [38]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [39]:
y_train

array([0, 0, 0, ..., 0, 0, 1], shape=(48100,))